// #define TIMER_BASE_ADDRESS 0x40000000
#define TIMER_CMP_LOWER_REG_OFFSET 0x10c
#define TIMER_CMP_UPPER_REG_OFFSET 0x110
#define TIMER_CONFIG_REG_OFFSET 0x100
#define TIMER_INTR_ENABLE_REG_OFFSET 0x114
#define TIMER_CNTRL_REG_OFFSET 0x0
#define TIMER_INTR_STATE_REG_OFFSET 0x118

void delay(int a);