#define PWM_BASE_ADDRESS 0x400b0000
#define PWM_DUTY_CYCLE_OFFSET 0xc
#define PWM_DUTY_CYCLE_OFFSET2 0x1c
#define PWM_CONTROL_REGISTER_OFFSET 0x0
#define PWM_DIVISOR_REGISTER_OFFSET 0x4
#define PWM_PERIOD_REGISTER_OFFSET 0x8
#define PWM_CONTROL_REGISTER_OFFSET2 0x10
#define PWM_DIVISOR_REGISTER_OFFSET2 0x14
#define PWM_PERIOD_REGISTER_OFFSET2 0x18
void PWM_DUTYCYCLE(int channel, int duty_cycle);
